version: '3.8'

services:
  # Railsアプリケーションのサービス定義
  web:
    build: .
    # サーバー起動コマンドを直接指定
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      # ボリュームマウントパスを hitonohagoromo に統一
      - .:/hitonohagoromo
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # PostgreSQLデータベースのサービス定義
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qol_closet_development
    ports:
      - "5432:5432"

# データを永続化するためのボリューム
volumes:
  postgres_data: