default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Dockerコンテナ間の通信設定をdefaultに統一
  host: db
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %> 

development:
  <<: *default
  database: hitonohagoromo_development

test:
  <<: *default
  database: hitonohagoromo_test

production:
  <<: *default 
  url: <%= ENV['DATABASE_URL'] %>
  # クラウド環境ではSSL接続が必須
  sslmode: 'require'