default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Dockerサービス名 'db' を指定
  host: db
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: hitonohagoromo_development

test:
  <<: *default
  database: hitonohagoromo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: 'require'